--Manufacturer database--
DROP TABLE if EXISTS MANUFACTURERHW5;

CREATE TABLE MANUFACTURERHW5(
	BID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20) NOT NULL,
	COUNTRY VARCHAR(50) NOT NULL,
	PRIMARY KEY(BID)
);

--sample data--
INSERT INTO MANUFACTURERHW5(NAME, COUNTRY) VALUES('Mazda','Japan');
INSERT INTO MANUFACTURERHW5(NAME, COUNTRY) VALUES('Chevrotlet','United States');
INSERT INTO MANUFACTURERHW5(NAME, COUNTRY) VALUES('Ford','United States');
INSERT INTO MANUFACTURERHW5(NAME, COUNTRY) VALUES('Mercedes-Benz','Germany');
INSERT INTO MANUFACTURERHW5(NAME, COUNTRY) VALUES('Honda','Japan');